/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://xjd4x7ncjbfzhooe4kb5t4sxty.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-clts2nmbs5cb3kejqnsr67l4fe",
    "aws_cognito_identity_pool_id": "us-east-1:80919ad6-326a-45a2-a1fe-69aa416f9418",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bRryeLVBf",
    "aws_user_pools_web_client_id": "3mubg7c79a912vhhvbfsfgrkkm",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "weeout01-storage-2ebbc512161600-main",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
